-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.films
(

    CONSTRAINT films_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.people
(

    CONSTRAINT people_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(

    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(

    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.reviews
    ADD FOREIGN KEY (id)
    REFERENCES public.films (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roles
    ADD FOREIGN KEY (film_id)
    REFERENCES public.films (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roles
    ADD FOREIGN KEY (id)
    REFERENCES public.people (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;